name: Unit Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - "v2/**"
      - "v3/**"
      - "v4/**"
  push:
    paths:
      - "v2/**"
      - "v3/**"
      - "v4/**"

jobs:
  test:
    name: Test plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        if: steps.changes.outputs.v2 == 'true' || steps.changes.outputs.v3 == 'true' || steps.changes.outputs.v4 == 'true' 
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            v2:
              - 'v2/**'
            v3:
              - 'v3/**'
            v4:
              - 'v4/**'

      - name: Run v2 tests
        if: steps.changes.outputs.v2 == 'true' || startsWith(github.ref,'refs/tags/v2')
        id: testsv2
        run: ./scripts/test.sh v2

      - name: Run v3 tests
        if: steps.changes.outputs.v3 == 'true' || startsWith(github.ref,'refs/tags/v3')
        id: testsv3
        run: ./scripts/test.sh v3

      - name: Run v4 tests
        if: steps.changes.outputs.v4 == 'true' || startsWith(github.ref,'refs/tags/v4')
        id: testsv4
        run: ./scripts/test.sh v4

      - name: Notify of test failure
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'github-actions'
          slack-message: "Plugins tests: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
