name: Run Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - "**"
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - name: Run test
        run: |
          echo "=============== list modified files ==============="
          echo "Base ref: $GITHUB_BASE_REF, Headref: $GITHUB_HEAD_REF"
          echo "Base ref: ${{ env.GITHUB_BASE_REF }}, Headref: $GITHUB_HEAD_REF"
          echo "Base ref: \$GITHUB_BASE_REF, Headref: \$GITHUB_HEAD_REF"
          
          git checkout -b $GITHUB_BASE_REF
          git checkout $GITHUB_HEAD_REF
          git branch --list
          git diff --name-only $(git merge-base --fork-point $GITHUB_BASE_REF)
